### ISSUE TITLE
This method will cause error in Android 11 or use MediaSore API

### ISSUE THREAD

**Issue by varun7952** [Kauavitorio/Squash_App#27]
https://github.com/Kauavitorio/Squash_App/blob/dc09e8420b887c142a604581d90eb9a8bd7cd2a7/app/src/main/java/dev/kaua/squash/Tools/Methods.java#L435

**Comment by Kauavitorio** [comment]
> https://github.com/Kauavitorio/Squash_App/blob/dc09e8420b887c142a604581d90eb9a8bd7cd2a7/app/src/main/java/dev/kaua/squash/Tools/Methods.java#L435

Thanks for your report, I'll be looking into

**Comment by Kauavitorio** [comment]
I believe this will solve it, tests were performed on several android versions, especially on 11 and everything went well.
